base_url: http://pod5.io
podcast_file_storage: http://s3.amazonaws.com/pod5podcast/
google_analytics_code: UA-XXXX
markdown: kramdown
site_title: ""
site_description: ""
site_logo: assets/images/logo@2x.png
feedburner_url: http://feed.pod.io