base_url: http://pod5.io
podcast_file_storage: http://pod5.s3.amazonaws.com/episodes/
podcast_file_bucket: pod5
google_analytics_code: UA-XXXX
markdown: kramdown
site_title: "Pod 5 Podcast"
site_description: "The 5 minute Objective-C Podcast"
site_logo: assets/images/logo@2x.png
feedburner_url: http://feed.pod.io